Hafazah/Controllers/LevelsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Hafazah.Common;
using Hafazah.DAL;
using Hafazah.Model.Entities.Program;

namespace Hafazah.Controllers
{
    public class LevelsController : BaseController
    {
        private HafazahDbContext db = new HafazahDbContext();

        // GET: Levels
        public ActionResult Index()
        {
            var levels = db.Levels.Include(l => l.Path).Where(l=>l.Path.ProgramType == Model.Enums.ProgramType.Fursan);
            return View(levels.ToList());
        }

        // GET: Levels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Level level = db.Levels.Find(id);
            if (level == null)
            {
                return HttpNotFound();
            }
            return View(level);
        }

        // GET: Levels/Create
        public ActionResult Create()
        {
            ViewBag.PathId = new SelectList(db.Paths.Where(p=>p.ProgramType == Model.Enums.ProgramType.Fursan), "Id", "Description");
            return View();
        }

        // POST: Levels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,LevelNumber,PathId,TotalPageNumber,PageFrom,PageTo,SurahFrom,SurahTo,QuranicVerseFrom,QuranicVerseTo,MaxNumberOfExcuses,Description,CreatedDate,UpdateDate,CreatedBy,UpdatedBy,IsDeleted")] Level level)
        {
            if (ModelState.IsValid)
            {
                db.Levels.Add(level);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PathId = new SelectList(db.Paths, "Id", "Name", level.PathId);
            return View(level);
        }

        // GET: Levels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Level level = db.Levels.Find(id);
            if (level == null)
            {
                return HttpNotFound();
            }
            ViewBag.PathId = new SelectList(db.Paths, "Id", "Name", level.PathId);
            return View(level);
        }

        // POST: Levels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LevelNumber,PathId,TotalPageNumber,PageFrom,PageTo,SurahFrom,SurahTo,QuranicVerseFrom,QuranicVerseTo,MaxNumberOfExcuses,Description,CreatedDate,UpdateDate,CreatedBy,UpdatedBy,IsDeleted")] Level level)
        {
            if (ModelState.IsValid)
            {
                db.Entry(level).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PathId = new SelectList(db.Paths, "Id", "Name", level.PathId);
            return View(level);
        }

        // GET: Levels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Level level = db.Levels.Find(id);
            if (level == null)
            {
                return HttpNotFound();
            }
            return View(level);
        }

    
        // POST: Levels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Level level = db.Levels.Find(id);
            db.Levels.Remove(level);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        #region Homeworks Section
        public ActionResult Homeworks(int? id)
        {
            ViewBag.BindLevelId = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var homeworks = db.LevelHomeworks.Where(h => h.LevelId == id).ToList();
            if (homeworks == null)
            {
                return HttpNotFound();
            }
            return View(homeworks);
        }

        [HttpGet]
        public JsonResult GetHomeworks(int levelId)
        {
            var homeworks = db.LevelHomeworks.Where(l => l.LevelId == levelId).ToList();
            return Json(homeworks, JsonRequestBehavior.AllowGet);
        }

        public JsonResult InsertHomeWorks(List<LevelHomework> homeworks)
        {
            //Truncate Table to delete all old records.
            db.Database.ExecuteSqlCommand("DELETE FROM [LevelHomeworks] WHERE LevelId =" + homeworks[0].LevelId);
            db.SaveChanges();
            //Check for NULL.
            if (homeworks == null)
            {
                homeworks = new List<LevelHomework>();
            }

            //Loop and insert records.
            foreach (var homework in homeworks)
            {
                db.LevelHomeworks.Add(homework);
            }
            int insertedRecords = db.SaveChanges();
            return Json(insertedRecords);
        }

        public ActionResult EditHomeWork(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var homework = db.LevelHomeworks.Include(p => p.Level).SingleOrDefault(x => x.Id == id);
            if (homework == null)
            {
                return HttpNotFound();
            }
            return View(homework);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditHomeWork(LevelHomework homework)
        {
            if (ModelState.IsValid)
            {
              
                db.Entry(homework).State = EntityState.Modified;
                db.SaveChanges();
                TempData["msg"] = TempData["msg"] = "<span class=\"label label-success\"> Updated Successfully </span>";
            }
            return View(homework);
        }
        #endregion
    }
}

Hafazah/Views/Levels/Create.cshtml
@model Hafazah.Model.Entities.Program.Level

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Level</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LevelNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LevelNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LevelNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PathId, "PathId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PathId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PathId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPageNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPageNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPageNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PageFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PageFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PageTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PageTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurahFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurahFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurahFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurahTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurahTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurahTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxNumberOfExcuses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxNumberOfExcuses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxNumberOfExcuses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hafazah/Views/Levels/Delete.cshtml
@model Hafazah.Model.Entities.Program.Level

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Level</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LevelNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LevelNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPageNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPageNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PageFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PageTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurahFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurahFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurahTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurahTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstimatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstimatedTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxNumberOfExcuses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxNumberOfExcuses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hafazah/Views/Levels/Details.cshtml
@model Hafazah.Model.Entities.Program.Level

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Level</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Path.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LevelNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LevelNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPageNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPageNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PageFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PageTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurahFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurahFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurahTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurahTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxNumberOfExcuses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxNumberOfExcuses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hafazah/Views/Levels/Edit.cshtml
@model Hafazah.Model.Entities.Program.Level

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Level</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LevelNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LevelNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LevelNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPageNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPageNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPageNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PageFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PageFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PageTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PageTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurahFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurahFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurahFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurahTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurahTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurahTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstimatedTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstimatedTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstimatedTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxNumberOfExcuses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxNumberOfExcuses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxNumberOfExcuses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hafazah/Views/Levels/Homeworks.cshtml
@model List<Hafazah.Model.Entities.Program.LevelHomework>

@{
    ViewBag.Title = "Homeworks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <table id="tblHomeworks" class="table" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th>OrderNumber</th>
                <th>SurahName</th>
                <th>RequiredMemorizedFrom</th>
                <th>RequiredMemorizedTo</th>
                <th>AbilityConnectFrom</th>
                <th>AbilityConnectTo</th>
                <th>ReviewFrom</th>
                <th>ReviewTo</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var homework in Model)
            {
            <tr>
                <td>@homework.OrderNumber</td>
                <td>@homework.SurahName</td>
                <td>@homework.RequiredMemorizedFrom</td>
                <td>@homework.RequiredMemorizedTo</td>
                <td>@homework.AbilityConnectFrom</td>
                <td>@homework.AbilityConnectTo</td>
                <td>@homework.ReviewFrom</td>
                <td>@homework.ReviewTo</td>
                <td><input type="button" class="btn btn-danger" value="Remove" onclick="Remove(this)" /></td>
                <td> @Html.ActionLink("Edit", "EditHomeWork", new { id = homework.Id }, htmlAttributes: new { @class = "btn btn-warning" }) </td>
            </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td><input class="form-control" type="text" id="txtOrderNumber" /></td>
                <td><input class="form-control" type="text" id="txtSurahName" /></td>
                <td><input class="form-control" type="text" id="txtRequiredMemorizedFrom" /></td>
                <td><input class="form-control" type="text" id="txtRequiredMemorizedTo" /></td>
                <td><input class="form-control" type="text" id="txtAbilityConnectFrom" /></td>
                <td><input class="form-control" type="text" id="txtAbilityConnectTo" /></td>
                <td><input class="form-control" type="text" id="txtReviewFrom" /></td>
                <td><input class="form-control" type="text" id="txtReviewTo" /></td>
                <td><input type="button" class="btn btn-primary" id="btnAdd" value="Add" /></td>
            </tr>
        </tfoot>
    </table>
    <br />
    <input type="button" id="btnSave" class="btn btn-success  btn-lg" value="Save All" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
    <script type="text/javascript">
        $("body").on("click", "#btnAdd", function () {
            //Reference the Name and Country TextBoxes.
            var txtOrderNumber = $("#txtOrderNumber");
            var txtSurahName = $("#txtSurahName");
            var txtRequiredMemorizedFrom = $("#txtRequiredMemorizedFrom");
            var txtRequiredMemorizedTo = $("#txtRequiredMemorizedTo");
            var txtAbilityConnectFrom = $("#txtAbilityConnectFrom");
            var txtAbilityConnectTo = $("#txtAbilityConnectTo");
            var txtReviewFrom = $("#txtReviewFrom");
            var txtReviewTo = $("#txtReviewTo");

            //Get the reference of the Table's TBODY element.
            var tBody = $("#tblHomeworks > TBODY")[0];

            //Add Row.
            var row = tBody.insertRow(-1);

            //Add RequiredMemorizedFrom cell.
            var cell = $(row.insertCell(-1));
            cell.html(txtOrderNumber.val());

            //Add SurahName cell.
            cell = $(row.insertCell(-1));
            cell.html(txtSurahName.val());

            //Add RequiredMemorizedTo cell.
            cell = $(row.insertCell(-1));
            cell.html(txtRequiredMemorizedFrom.val());

            //Add RequiredMemorizedTo cell.
            cell = $(row.insertCell(-1));
            cell.html(txtRequiredMemorizedTo.val());

            //Add AbilityConnectFrom cell.
            cell = $(row.insertCell(-1));
            cell.html(txtAbilityConnectFrom.val());

            //Add AbilityConnectTo cell.
            cell = $(row.insertCell(-1));
            cell.html(txtAbilityConnectTo.val());

            //Add ReviewFrom cell.
            cell = $(row.insertCell(-1));
            cell.html(txtReviewFrom.val());

            //Add ReviewTo cell.
            cell = $(row.insertCell(-1));
            cell.html(txtReviewTo.val());

            //Add Button cell.
            cell = $(row.insertCell(-1));
            var btnRemove = $("<input />");
            btnRemove.attr("type", "button");
            btnRemove.attr("onclick", "Remove(this);");
            btnRemove.attr("class", "btn btn-danger");
            btnRemove.val("Remove");
            cell.append(btnRemove);

            //Clear the TextBoxes.
            txtOrderNumber.val("");
            txtSurahName.val("");
            txtRequiredMemorizedFrom.val("");
            txtRequiredMemorizedTo.val("");
            txtAbilityConnectFrom.val("");
            txtAbilityConnectTo.val("");
            txtReviewFrom.val("");
            txtReviewTo.val("");

        });

        function Remove(button) {
            //Determine the reference of the Row using the Button.
            var row = $(button).closest("TR");
            var name = $("TD", row).eq(0).html();
            if (confirm("Do you want to delete: " + name)) {
                //Get the reference of the Table.
                var table = $("#tblHomeworks")[0];

                //Delete the Table row using it's Index.
                table.deleteRow(row[0].rowIndex);
            }
        };

        $("body").on("click", "#btnSave", function () {
            //Loop through the Table rows and build a JSON array.
            var homeworks = new Array();
            $("#tblHomeworks TBODY TR").each(function () {
                var row = $(this);
                var homework = {};
                homework.OrderNumber = row.find("TD").eq(0).html();
                homework.SurahName = row.find("TD").eq(1).html();
                homework.RequiredMemorizedFrom = row.find("TD").eq(2).html();
                homework.RequiredMemorizedTo = row.find("TD").eq(3).html();
                homework.AbilityConnectFrom = row.find("TD").eq(4).html();
                homework.AbilityConnectTo = row.find("TD").eq(5).html();
                homework.ReviewFrom = row.find("TD").eq(6).html();
                homework.ReviewTo = row.find("TD").eq(7).html();
                homework.LevelId=@ViewBag.BindLevelId
                homeworks.push(homework);
            });

            //Send the JSON array to Controller using AJAX.
            $.ajax({
                type: "POST",
                url: '@Url.Action("InsertHomeWorks", "Levels")',
                data: JSON.stringify(homeworks),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r) {
                    alert(r + " record(s) inserted.");
                }
            });
        });
    </script>
</body>
</html>