Hafazah/Controllers/MembersController.cs
using Hafazah.Common;
using Hafazah.DAL;
using Hafazah.Model;
using Hafazah.Services;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Hafazah.Controllers
{
    public class MembersController : BaseController
    {
        private HafazahDbContext _db = new HafazahDbContext();

        #region Index  (Dashboard)
        [HttpGet]
        public ActionResult ChangeRegistrationStatus()
        {
            var obj = _db.GlobalValues.Single(x => x.Key == "ChangeRegistrationStatus");
            if (obj.Value == "true")
                obj.Value = "false";
            else
                obj.Value = "true";
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult UpdateWaveNumber(string wavenumber)
        {
            var obj = _db.GlobalValues.Single(x => x.Key == "WaveNumber");
            obj.Value = wavenumber;
            _db.SaveChanges();
            return Json(true);
        }

        // GET: Members
        [Route("Dashboard")]
        public ActionResult Index(string filterMembers = "Registered Members", string phoneNumber = "")
        {
            if (IsLoggedIn())
            {
                if (User.IsInRole("Admin"))
                {
                    InitializationValues();
                    FillingDDL();
                    SetRegistrationStatus();
                    return View(GetFilteredList(filterMembers, phoneNumber));
                }
                else
                    return RedirectToAction("UnAuthorized");
            }
            else
                return RedirectToAction("Login", "Account");
        }

        private bool IsLoggedIn()
        {
            string currentUsername = User.Identity.GetUserName();
            return !string.IsNullOrEmpty(currentUsername);
        }
        private void InitializationValues()
        {
            ViewBag.IsRegistrationOpen = false;
            ViewBag.IsAdmin = User.IsInRole("Admin");
        }
        private void FillingDDL()
        {
            var memberSearchedFilter = new List<string>()
            {
                 @Resources.GetResource.T("RegisteredMembers"),
                 @Resources.GetResource.T("PendingRequests")
            };

            ViewBag.MembersDDLFilter = memberSearchedFilter;
        }
        private void SetRegistrationStatus()
        {
            if (ViewBag.IsAdmin)
            {
                var registrationStatus = _db.GlobalValues.Single(x => x.Key == "ChangeRegistrationStatus");

                if (registrationStatus.Value == "true")
                    ViewBag.IsRegistrationOpen = true;


                var waveNumber = _db.GlobalValues.Single(x => x.Key == "WaveNumber");
                ViewBag.WaveNumber = waveNumber.Value;
            }
        }



        [Route("UnAuthorized")]
        public ActionResult UnAuthorized()
        {
            return View();
        }
        public List<Member> GetFilteredList(string filterMembers, string phoneNumber)
        {
            IQueryable<Member> query = Enumerable.Empty<Member>().AsQueryable();

            if (filterMembers == "Registered Members" || filterMembers == Resources.GetResource.T("RegisteredMembers"))
            {
                query = _db.Members.Where(x => x.IsActive == true);
                ViewBag.ShowIsActiveColumn = false;
            }

            if (filterMembers == "Pending Requests" || filterMembers == Resources.GetResource.T("PendingRequests"))
            {
                query = _db.Members.Where(x => x.IsActive == false);
                ViewBag.ShowIsActiveColumn = true;
            }

            if (!string.IsNullOrEmpty(phoneNumber))
                query = _db.Members.Where(x => x.PhoneNumber.Contains(phoneNumber.Trim()));

            return query.ToList();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = _db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();

            }
            return View(member);
        }

        public ActionResult Approve(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = _db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }

            return RedirectToAction("ApproveNewMember", "Account", member);
        }
        #endregion



        #region Edit Page
        [Route("EditMember")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = _db.Members.Find(id);
            ViewBag.InstrcutorId = new SelectList(_db.Instructors, "Id", "LastName", member.InstrcutorId);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("EditMember")]
        public ActionResult Edit(
            [Bind(Include = "Id,FirstName,SecondName,ThirdName,LastName,Gender,BirthDate,EducationLevelId,JobTitle,PhoneNumber,Email,IsActive,InstrcutorId")] Member member)
        {
            ViewBag.InstrcutorId = new SelectList(_db.Instructors, "Id", "LastName");
            try
            {
                // Update Values 
                Member obj = _db.Members.Find(member.Id);
                obj.FirstName = member.FirstName;
                obj.SecondName = member.SecondName;
                obj.ThirdName = member.ThirdName;
                obj.LastName = member.LastName;
                obj.Gender = member.Gender;
                obj.BirthDate = member.BirthDate;
                obj.EducationLevelId = member.EducationLevelId;
                obj.JobTitle = member.JobTitle;
                obj.PhoneNumber = member.PhoneNumber;
                obj.IsActive = member.IsActive;
                obj.InstrcutorId = member.InstrcutorId;

                _db.Entry(obj).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {
                return View(member);
            }
        }

        #endregion

        #region Delete Action

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = _db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = _db.Members.Find(id);
            _db.Members.Remove(member);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region Create Page 

        [Route("Registration")]
        public ActionResult Create()
        {
            var obj = _db.GlobalValues.Single(x => x.Key == "ChangeRegistrationStatus");

            if (obj.Value == "true")
            {
                ViewBag.IsRegistrationOpen = true;
                FillingDDLs();
                SetDefautValuesForValidations();
            }
            else
                ViewBag.IsRegistrationOpen = false;

            return View();
        }

        [HttpPost]
        [Route("Registration")]
        public ActionResult Submit(Member member)
        {
            if (member.PathId <= 0 || member.ProgramType == Model.Enums.ProgramType.NotSet)
                return RedirectToAction("Create");

            SharedServices sharedServices = new SharedServices();
            if (ModelState.IsValid && !sharedServices.IsUsernameToken(member.Username) && !sharedServices.IsEmaiAlreadylExists(member.Email) && !sharedServices.IsPhoneNumberAlreadylExists(member.PhoneNumber))
            {
                _db.Members.Add(member);
                _db.SaveChanges();
                return RedirectToAction("ThankYou");
            }
            return RedirectToAction("SomeErrorHappend");
        }

        private void FillingDDLs()
        {
            // Filling DDls
            ViewBag.EducationLevelId = new SelectList(_db.EducationLevels, "Id", "Name");
            ViewBag.QuranMemorizedId = new SelectList(_db.QuranMemorized, "Id", "Name");
            if (IsEn)
                ViewBag.CountryId = new SelectList(_db.Countries, "Id", "NameEn");
            else
                ViewBag.CountryId = new SelectList(_db.Countries, "Id", "NameAr");

        }

        private void SetDefautValuesForValidations()
        {
            // Validation
            ViewBag.FirstNameMissing = true;
            ViewBag.LastNameMissing = true;
            ViewBag.GenderNameMissing = true;
            ViewBag.CountryIdMissing = true;
            ViewBag.AddressMissing = true;
            ViewBag.BirthDateMissing = true;
            ViewBag.EducationLevelIdMissing = true;
            ViewBag.JobTitleMissing = true;
            ViewBag.KnownFromMissing = true;
            ViewBag.PhoneNumberMissing = true;
            ViewBag.EmailMissing = true;
            ViewBag.UsernameMissing = true;
            ViewBag.SuggestPasswordMissing = true;
            ViewBag.QuranMemorizedIdMissing = true;
            ViewBag.InterviewDateMissing = true;
            ViewBag.ProgramTypeMissing = true;

Hafazah/Views/Members/Delete.cshtml
@model Hafazah.Model.Member

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThirdName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThirdName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuranMemorized)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuranMemorized)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterviewDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KnownFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KnownFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hafazah/Views/Members/Details.cshtml
@model Hafazah.Model.Member

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instrcutor.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instrcutor.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThirdName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThirdName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SuggestPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SuggestPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuranMemorized)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuranMemorized)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterviewDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KnownFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KnownFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgramType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WarningCounter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WarningCounter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccomplishedPages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccomplishedPages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastSent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastSent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NotificationToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NotificationToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilePictureBase64)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilePictureBase64)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hafazah/Views/Members/Index.cshtml
@model IEnumerable<Hafazah.Model.Member>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@*    @Html.ActionLink("Create New", "Create")*@

@if (ViewBag.IsAdmin)
{
    <h2>@Resources.GetResource.T("Dashboard")</h2>
    if (ViewBag.IsRegistrationOpen)
    {
        <label>
            @Resources.GetResource.T("RegistrationStatusOn")
        </label>
        <input type="button" class="btn btn-danger " value="@Resources.GetResource.T("Deactivate")" onclick="location.href='@Url.Action("ChangeRegistrationStatus", "Members")'" />
    }
    else
    {
        <label>
            @Resources.GetResource.T("RegistrationStatusOff")
        </label>
        <input type="button" class="btn btn-success" value="@Resources.GetResource.T("Active")" onclick="location.href='@Url.Action("ChangeRegistrationStatus", "Members")'" />
    }

    <br />
    <br />

    <div class="form-group-sm" style="text-align:end">
        <label>
            @Resources.GetResource.T("CurrentWaveNumber")
        </label>
        <input id="waveNumberInput" type="text" value="@(ViewBag.WaveNumber ?? String.Empty)" >
        <input type="button" class="btn btn-warning" value="@Resources.GetResource.T("Edit")" onclick="updateWaveNumber()"  />

    </div>
    <hr />

    using (Html.BeginForm("Index", "Members", FormMethod.Get))
    {
        <text>@Resources.GetResource.T("ShowMembers") </text> @Html.DropDownList("filterMembers", new SelectList(ViewBag.MembersDDLFilter), new { id = "ddl", @class = "form-control" })
        <text>@Resources.GetResource.T("SearchPhoneNumber")</text>
        {
            @Html.TextBox("phoneNumber", null, new { id = "SearchBox", @class = "form-control" })
        }
        <br />
        <input class="btn btn-info" type="submit" value="@Resources.GetResource.T("Search")" />
    }
    <br />
    <br />

    <table class="table table-striped" style="text-align:inherit">
        <tr>
            <th>
                @Html.DisplayName(@Resources.GetResource.T("WaveNumber"))
            </th>
            <th>
                @Html.DisplayName(@Resources.GetResource.T("FirstName"))
            </th>
            <th>
                @Html.DisplayName(@Resources.GetResource.T("LastName"))
            </th>

            <th>
                @Html.DisplayName(@Resources.GetResource.T("Age"))
            </th>

            <th>
                @Html.DisplayName(@Resources.GetResource.T("PhoneNumber"))
            </th>


            @if (ViewBag.ShowIsActiveColumn == true)
            {
                <th>
                    @Resources.GetResource.T("Approve")
                </th>
            }

            @if (ViewBag.ShowIsActiveColumn == false)
            {
                <th>
                    @Resources.GetResource.T("IsActive")
                </th>
            }
            <th>
                @Resources.GetResource.T("Actions")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.WaveNumber)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>

                @if (!ViewBag.ShowIsActiveColumn)
                {

                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                }
                @if (ViewBag.ShowIsActiveColumn)
                {
                    <td>
                        @Html.ActionLink(@Resources.GetResource.T("Approve"), "Approve", new { id = item.Id }, new { @style = "color:green" })
                        @*|@Html.ActionLink("Decline", "Decline", new { id = item.Id }, new { @style = "color:red" })*@
                    </td>
                }
                <td>
                    @Html.ActionLink(@Resources.GetResource.T("Edit"), "Edit", new { id = item.Id }) |
                    @Html.ActionLink(@Resources.GetResource.T("Details"), "Details", new { id = item.Id }) |
                    @Html.ActionLink(@Resources.GetResource.T("Delete"), "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

}

<script type="text/javascript">

    function updateWaveNumber() {
        var e = document.getElementById("waveNumberInput");
        var waveNumber= e.value;
        if (waveNumber.length > 0) {
             $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateWaveNumber", "Members")',
                 data: JSON.stringify({ "waveNumber": waveNumber }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r) {
                    if (r == true) {
                        $("#lblWaveNumber").show();
                    }
                    setTimeout(function () {
                        $("#lblWaveNumber").hide();
                    }, 2000);
                }
            });
        }

    }

</script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hafazah/Views/Members/SomeErrorHappend.cshtml
@{
    ViewBag.Title = "SomeErrorHappend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Some Error Happend</h2>

Hafazah/Views/Members/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Resources.GetResource.T("ThankYou")</h2>

Hafazah/Views/Members/UnAuthorized.cshtml
@{
    ViewBag.Title = "UnAuthorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You Don't have permission on web app , you can only use the application on your phone</h2>